name: Run BACEN Data Script

on:
  workflow_dispatch:
  schedule:
    - cron: '17 12 6 3 *'  # March 6th, 9:17 AM São Paulo (UTC-3)
    - cron: '19 12 7 4 *'  # April 7th, 9:19 AM São Paulo (UTC-3)

jobs:
  run_script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget r-cran-openxlsx r-cran-furrr r-cran-future r-cran-future.apply r-cran-future.batchtools r-cran-lubridate r-cran-purrr r-cran-purrrlyr r-cran-purrrogress r-cran-readxl r-cran-tibble r-cran-tidyverse r-cran-littler -y

      - name: Run R script
        run: sudo Rscript bacen/scripts/102_bacen_ETL_v01_download_simples.R

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update bacen data"
          file_pattern: bacen/lake/*.xlsx bacen/lake/*.rdata
